### ISSUE TITLE
All ladders are one-time use

### ISSUE THREAD

**Issue by prototype464** [Scooxstad/SnakeEater#1]
Did some extensive testing and found out this mod in specific is causing ladders to be one-time use (might have something to do with the text change after a ladder is used once?). Previously I thought it only affected the ship's ladders but a friend of mine just confirmed it affects environmental and extension ladders as well.

If you'd like to test it yourself, here's the R2ModManager code: **0191863b-792f-dd6a-a94d-c35c3a29bfbe**

**Comment by Scooxstad** [comment]
It was indeed a stray NullPointerException that I had not caught during the last hotfix, thanks for reporting!
